#!/bin/bash

## Description: Run deployer CLI command
## Usage: dep [flags] [args]
## Example: "ddev dep deploy <target>"
## ProjectTypes: laravel, php
## ExecRaw: true

# TODO: use better path if vendor/ is somewhere else
/var/www/html/vendor/bin/dep  "$@"

# Deployer must be installed via 'ddev composer require --dev deployer/deployer:^7', otherwise this won't work
